abbr -a -g -- aar 'sudo apt autoremove'
abbr -a -g -- adu 'sudo apt dist-upgrade'
abbr -a -g -- ai 'sudo apt install'
abbr -a -g -- al 'apt list'
abbr -a -g -- aq 'apt search'
abbr -a -g -- au 'sudo apt update'
