abbr -a -g -- ga 'git add -A'
abbr -a -g -- gb 'git branch'
abbr -a -g -- gca 'git commit --amend'
abbr -a -g -- gc 'git commit'
abbr -a -g -- gcm 'git commit -m'
abbr -a -g -- gcob 'git checkout -b'
abbr -a -g -- gco 'git checkout'
abbr -a -g -- gd 'git diff'
abbr -a -g -- gf 'git fetch'
abbr -a -g -- gfp 'git fetch --prune'
abbr -a -g -- gg 'git grep -i -e'
abbr -a -g -- gh 'git --help'
abbr -a -g -- gl 'git log'
abbr -a -g -- gpa 'git pull --all'
abbr -a -g -- gpf 'git push --force'
abbr -a -g -- gp 'git push'
abbr -a -g -- gpo 'git push --set-upstream origin (git branch --show-current)'
abbr -a -g -- gsb 'git switch'
abbr -a -g -- gs 'git status'
abbr -a -g -- gsh 'git show'
